apiVersion: tekton.dev/v1
kind: PipelineRun
metadata: { name: build-and-push-simulators-run }
spec:
  pipelineRef: { name: build-and-push-simulators }
  params:
  - { name: registry, value: ghcr.io/tmwaas/telco-cloud-project }
  - { name: commit, value: manual }
  workspaces:
  - name: source
    volumeClaimTemplate:
      metadata: { name: source-ws }
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources: { requests: { storage: 2Gi } }
