image:
  repository: "tmwaas/ran-sim"        
  tag: "dev"               
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  port: 80

env:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "debug"

readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 5

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
