apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-sim
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    namespace: ns-core
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tmwaas/Telco-Cloud-Project.git
    targetRevision: main
    path: charts/core-sim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
