apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ran-sim-role
  namespace: ns-ran
rules:
- apiGroups: [""]
  resources: ["secrets", "pods", "services", "configmaps", "ingresses", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]