apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ran-sim-rolebinding
  namespace: ns-ran
subjects:
- kind: User
  name: tmwaas
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ran-sim-role
  apiGroup: rbac.authorization.k8s.io