apiVersion: apps/v1
kind: Deployment
metadata:
  name: ran-sim
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ran-sim
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ran-sim
    spec:
      restartPolicy: Always

      {{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - name: ran-sim
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        env:
{{ toYaml .Values.env | nindent 10 }}
        ports:
        - containerPort: 8000
          name: http

        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
{{ toYaml .Values.resources | nindent 10 }}

        {{- with .Values.securityContext }}
        securityContext:
{{ toYaml . | nindent 10 }}
        {{- end }}