apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-sim
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: core-sim
  template:
    metadata:
      labels:
        app: core-sim
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: core-sim
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: 8000
            name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: core-sim
  labels:
    app: core-sim
spec:
  selector:
    app: core-sim
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 8000
