stages: [lint, build, push, deploy]
variables: { IMAGE_TAG: "$CI_COMMIT_SHORT_SHA" }
lint:
  stage: lint
  image: python:3.11-slim
  script: [ "pip install ruff", "ruff apps/**/src || true" ]
build:
  stage: build
  image: docker:25.0.3
  services: [docker:25.0.3-dind]
  script:
    - docker build -t $CI_REGISTRY_IMAGE/ran-sim:$IMAGE_TAG apps/ran-sim
    - docker build -t $CI_REGISTRY_IMAGE/core-sim:$IMAGE_TAG apps/core-sim
push:
  stage: push
  image: docker:25.0.3
  services: [docker:25.0.3-dind]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/ran-sim:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/core-sim:$IMAGE_TAG
deploy:
  stage: deploy
  image: alpine:3.19
  script:
    - apk add --no-cache yq git
    - yq -i '.image.tag = env(IMAGE_TAG)' charts/ran-sim/values.yaml
    - yq -i '.image.tag = env(IMAGE_TAG)' charts/core-sim/values.yaml
    - git config user.email "ci@example.com"; git config user.name "gitlab-ci"
    - git add charts/*/values.yaml && git commit -m "bump charts to $IMAGE_TAG" || true
