apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telcocloud-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tmwaas/Telco-Cloud-Project.git
    targetRevision: main
    path: gitops/argocd/apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
